import { WalkthroughSlide } from '../../components/WalkthroughSlide'

export function MlxLaunch() {
  return (
    <WalkthroughSlide
      title="Launching Distributed Jobs"
      code={`# Launch with hostfile
mlx.launch --verbose \\
  --hostfile hostfile.json \\
  -n 2 \\
  test_mlx_mpi.py

# Launch with direct hosts
mlx.launch --verbose \\
  --hosts 192.168.1.100,192.168.1.101 \\
  -n 2 \\
  test_mlx_mpi.py

# What happens under the hood:
# 1. SSH into each Mac
# 2. Start MPI processes
# 3. Set up ring communication
# 4. Run the script on each rank
# 5. Aggregate results`}
      steps={[
        {
          lines: [1, 5] as [number, number],
          description: 'Launch using the hostfile generated by distributed_config. The -n flag specifies how many processes (one per Mac).',
        },
        {
          lines: [7, 11] as [number, number],
          description: 'Alternative: pass host IPs directly instead of a hostfile. Same effect, more convenient for quick testing.',
        },
        {
          lines: [13, 18] as [number, number],
          description: 'Under the hood: mlx.launch SSHs into each Mac, starts MPI processes, establishes the ring, runs your script, and handles communication.',
        },
      ]}
    />
  )
}
